### PR TITLE
fix: update underscore to resolve security issues

### PR DESCRIPTION
**Pull request by jeffal**
- update underscore to resolve security issues

[See advisory in GitHub Advisory Database](https://github.com/advisories/GHSA-cxjh-pqwp-8mfp)

### CODE REVIEW

**Comment by jeffal** [comment]
cc @evxn @wickedest Thank you! 🙏

**Comment by jeffal** [comment]
@evxn Would you be able to merge this change?

**Comment by evxn** [comment]
Hey, @jeffal. Thanks for your contribution. @misternerd should probably have the merge rights. But first, I have some small suggestions to your patch:
1. Can you update underscore.js to the most recent version (`1.13.6` at the moment);
2. Please, reset the changes to `jsonpath.min.js`, `jsonpath.js` cause they're hard to review and verify. I've end up with different hash sums when trying it out on my local machine. 
3. Commit only `package.json` changes, so that the lib code can be generated and published directly by a maintainer.

**Comment by evxn** [comment]
Hey, @jeffal. Thanks for your submission. @misternerd should probably have the merge rights. But first, I have some small suggestions to your patch:

1. Can you update underscore.js to the most recent version (1.13.6 at the moment);
2. Please, reset the changes to jsonpath.min.js, jsonpath.js cause they're hard to review and verify. I've end up with different hash sums when trying it out on my local machine.
3. Commit only package.json changes, so that the lib code can be generated and published directly by a maintainer.

**Comment by jeffal** [comment]
@evxn Updated! Thank you for the suggestions.

@misternerd Please merge if you approve these changes. Thanks!

**Review by misternerd — APPROVED** [review]

**Comment by misternerd** [comment]
Thanks for the PR @jeffal. And sorry for the delay, I didn't realize I was still a maintainer here.

**Pull request merged**
